### ISSUE TITLE
Exporting the operator 'aten::_upsample_bilinear2d_aa' to ONNX opset version 17 is not supported

### ISSUE THREAD

**Issue by yang2021** [xiuqhou/Salience-DETR#17]
raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_upsample_bilinear2d_aa' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::_upsample_bilinear2d_aa' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>
导出onnx模型时报错，这个怎么解决

**Comment by xiuqhou** [comment]
请将[base_detector.py](https://github.com/xiuqhou/Salience-DETR/blob/main/models/detectors/base_detector.py)第70行的antialias参数设置为False再进行导出

**Comment by yang2021** [comment]
@xiuqhou 谢谢 已成功解决
