### ISSUE TITLE
程序环境配置

### ISSUE THREAD

**Issue by z972778371** [xiuqhou/Salience-DETR#2]
按照readme进行到 conda install --file requirements.txt这一步的时候，程序一直在Solving environment:/
持续跳
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

尝试换清华源或默认源还是这样
请问这正常么？有没有什么好的解决办法？？

**Comment by xiuqhou** [comment]
感谢您的关注！conda环境依赖解析过程比较慢，这是正常的。如果解析时间非常长，可以尝试使用mamba或pip安装。
1. 如果使用mamba，请先安装mamba：

```shell
conda install mamba -c conda-forge   # 使用conda安装mamba，等待时间不会太长
mamba install --file requirements.txt -c conda-forge  # 后续命令将conda替换成mamba运行
```

3. 使用pip安装，pip对于依赖的解析方式和conda不同，可能会导致accelerate框架和pytorch框架版本不对应，但一般情况下没问题：

```shell
pip install -r requirements.txt
```

**Comment by z972778371** [comment]
> 感谢您的关注！conda环境依赖解析过程比较慢，这是正常的。如果解析时间非常长，可以尝试使用mamba或pip安装。
> 
> 1. 如果使用mamba，请先安装mamba：
> 
> ```shell
> conda install mamba -c conda-forge   # 使用conda安装mamba，等待时间不会太长
> mamba install --file requirements.txt -c conda-forge  # 后续命令将conda替换成mamba运行
> ```
> 
> 3. 使用pip安装，pip对于依赖的解析方式和conda不同，可能会导致accelerate框架和pytorch框架版本不对应，但一般情况下没问题：
> 
> ```shell
> pip install -r requirements.txt
> ```

感谢答复，尝试了mamba，等待时间还是十分的长，未能成功安装mamba，最终还是选择pip完成了环境安装
