### ISSUE TITLE
关于salience_detr中L174-L176的position_embedding计算

### ISSUE THREAD

**Issue by autoencoder-zz** [xiuqhou/Salience-DETR#37]
### Question

作者您好，在阅读代码过程中我有一些地方没搞懂，向您请教一下

主要是关于position_embedding计算，我有一些疑问

在L166返回的mask的shape应该是[bs, h, w]

经过L175的插值之后，列表中添加的mask的shape是[1,bs,h,w]

在L176调用PositionEmbeddingSine函数，此时该函数下的

        y_embed = not_mask.cumsum(1, dtype=torch.float32)
        x_embed = not_mask.cumsum(2, dtype=torch.float32)

这里的位次计数，y对应的h应该是dim2，x对应的w应该是dim3吧？

是不是我理解哪里有问题，故向您请教一下

期待您早日答复，谢谢

**Comment by xiuqhou** [comment]
L175插值后返回的是[1，b，h，w]，后面还有个索引[0]的操作，所以输入进position_encoding的mask维度是[b，h，w]

**Comment by autoencoder-zz** [comment]
> L175插值后返回的是[1，b，h，w]，后面还有个索引[0]的操作，所以输入进position_encoding的mask维度是[b，h，w]
昨天dubug看到了，感谢答复
