### ISSUE TITLE
--mixed-precision=fp16 传参配置未修改的问题

### ISSUE THREAD

**Issue by autoencoder-zz** [xiuqhou/Salience-DETR#40]
### Question

利用命令行传参混合精度，运行程序后显示的配置一直是no
```python
CUDA_VISIBLE_DEVICES=0,1 accelerate launch main.py --mixed-precision=fp16
``` 
![image](https://github.com/user-attachments/assets/b5aa40a3-ce56-4f0d-b2a0-0faf11e65150)

另外想问一下，fp16可以提升模型性能和训练速度吗？

**Comment by xiuqhou** [comment]
图片显示的是accelerate启动脚本的参数，不是传给main.py文件的参数。您的命令没问题，参数`--mixed-precision fp16`已经传进去了，main.py文件参数请看输出的Command line arguments，大概是这样：

![图片](https://github.com/user-attachments/assets/00ab4cbd-f980-440d-8dad-59c25d04819a)

`--mixed-precision`参数可以设置`fp16`和`bf16`，都可以提升模型训练速度和减少训练过程中的显存占用，bf16更不容易出现数值溢出问题。

**Comment by autoencoder-zz** [comment]
> 图片显示的是accelerate启动脚本的参数，不是传给main.py文件的参数。您的命令没问题，参数`--mixed-precision fp16`已经传进去了，main.py文件参数请看输出的Command line arguments，大概是这样：
> 
> ![图片](https://private-user-images.githubusercontent.com/49118282/363151448-00ab4cbd-f980-440d-8dad-59c25d04819a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjI4NTYsIm5iZiI6MTcyNTAyMjU1NiwicGF0aCI6Ii80OTExODI4Mi8zNjMxNTE0NDgtMDBhYjRjYmQtZjk4MC00NDBkLThkYWQtNTljMjVkMDQ4MTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDEyNTU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmZWUwNTZjZmRlMDhiM2E2NjAxYjM2ZmI4OWRjMzMxNTM2MWFiNjdlYzMzNGQ5MGI4ZWZiNzI2NjE2NTM2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DfBofu2um7KULhY-UuABb7lKWuSRDplayrDI0nyw0iQ)
> 
> `--mixed-precision`参数可以设置`fp16`和`bf16`，都可以提升模型训练速度和减少训练过程中的显存占用，bf16更不容易出现数值溢出问题。

好的，谢谢你的回答！
