### ISSUE TITLE
loss_salience收敛较快

### ISSUE THREAD

**Issue by yongL1nk** [xiuqhou/Salience-DETR#43]
### Question

我使用自己的数据集进行训练时，发现loss_salience初始化时相对较大，但经过几十个轮次就能降低到1以下，大概是0.0几的样子，请问这是正常的吗？还是表明我计算loss时的输入数据存在问题？

**Comment by xiuqhou** [comment]
Hi @yongL1nk 

这是正常的现象，我在训练的时候也是初始loss_salience大概几十，很快就下降到零点几了。

**Comment by yongL1nk** [comment]
好的，感谢您的回复！
