### ISSUE TITLE
关于修改评估指标（APs，APm，APl）的问题

### ISSUE THREAD

**Issue by autoencoder-zz** [xiuqhou/Salience-DETR#47]
### Question

作者您好，我想请问一些模型flops计算的代码可以共享一下吗？谢谢！

**Comment by autoencoder-zz** [comment]
我看到coco_eval.py中调用了COCOeval，是不是直接在COCOeval中直接修改areaRng参数就可以了？

**Comment by xiuqhou** [comment]
FLOPs计算的代码已经release了，是`tools/benchmark_model.py`

**Comment by autoencoder-zz** [comment]
> FLOPs计算的代码已经release了，是`tools/benchmark_model.py`

好的谢谢
