### ISSUE TITLE
推理结果的可视化

### ISSUE THREAD

**Issue by 566aaa** [xiuqhou/Salience-DETR#55]
### Question

进行推理结果的可视化，怎样只可视化置信度最高的预测框呢

**Comment by xiuqhou** [comment]
可以修改PostProcess的`nms_iou_threshold`和`confidence_score`，把低置信度的检测框过滤掉

**Comment by 566aaa** [comment]
您方便给我举例说明吗，PostProcess中的select_box_nums_for_evaluation；confidence_score；nms_iou_threshold。还有就是和inference.py中的--show-conf有冲突 或者区别吗，感谢您！
